package com.github.aro_tech.interface_it.util.mixin;

import org.mockito.Matchers; 

/** 
 * Wrapper of static elements in org.mockito.Matchers
 * Generated by Interface-It: https://github.com/aro-tech/interface-it
 * {@link org.mockito.Matchers}
 */
public interface MatchersMixin {


    // CONSTANTS: 


    // DELEGATE METHODS: 

}